# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 709)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../8ac35b44/note.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.MainLayout = QtWidgets.QWidget(MainWindow)
        self.MainLayout.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(86, 59, 95, 255), stop:1 rgba(128, 86, 146, 255));")
        self.MainLayout.setObjectName("MainLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MainLayout)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftColumn = QtWidgets.QVBoxLayout()
        self.LeftColumn.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.LeftColumn.setSpacing(6)
        self.LeftColumn.setObjectName("LeftColumn")
        self.createNote = QtWidgets.QPushButton(self.MainLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createNote.sizePolicy().hasHeightForWidth())
        self.createNote.setSizePolicy(sizePolicy)
        self.createNote.setMinimumSize(QtCore.QSize(250, 30))
        self.createNote.setMaximumSize(QtCore.QSize(250, 30))
        self.createNote.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.createNote.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(106, 79, 115, 255), stop:1 rgba(128, 86, 146, 255));\n"
"border: 2px solid rgb(65,48, 70);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../94df6902/file-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createNote.setIcon(icon1)
        self.createNote.setObjectName("createNote")
        self.LeftColumn.addWidget(self.createNote)
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.searchLayout.setContentsMargins(-1, -1, -1, 0)
        self.searchLayout.setObjectName("searchLayout")
        self.searchNoteTxt = QtWidgets.QLineEdit(self.MainLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchNoteTxt.sizePolicy().hasHeightForWidth())
        self.searchNoteTxt.setSizePolicy(sizePolicy)
        self.searchNoteTxt.setMinimumSize(QtCore.QSize(155, 30))
        self.searchNoteTxt.setMaximumSize(QtCore.QSize(155, 30))
        self.searchNoteTxt.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(66, 39, 75, 255), stop:1 rgba(86, 59, 95, 255));\n"
"border: 2px solid rgb(65,48, 70);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);")
        self.searchNoteTxt.setDragEnabled(False)
        self.searchNoteTxt.setObjectName("searchNoteTxt")
        self.searchLayout.addWidget(self.searchNoteTxt)
        self.searchButton = QtWidgets.QPushButton(self.MainLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setMinimumSize(QtCore.QSize(85, 30))
        self.searchButton.setMaximumSize(QtCore.QSize(85, 30))
        self.searchButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(106, 79, 115, 255), stop:1 rgba(128, 86, 146, 255));\n"
"border: 2px solid rgb(65,48, 70);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../e1e6096a/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon2)
        self.searchButton.setObjectName("searchButton")
        self.searchLayout.addWidget(self.searchButton)
        self.LeftColumn.addLayout(self.searchLayout)
        self.notesList = QtWidgets.QListWidget(self.MainLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notesList.sizePolicy().hasHeightForWidth())
        self.notesList.setSizePolicy(sizePolicy)
        self.notesList.setMaximumSize(QtCore.QSize(250, 16777215))
        self.notesList.setStatusTip("")
        self.notesList.setWhatsThis("")
        self.notesList.setAccessibleName("")
        self.notesList.setAccessibleDescription("")
        self.notesList.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(66, 39, 75, 255), stop:1 rgba(106, 79, 115, 255));\n"
"border: 2px solid rgb(65,48, 70);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);")
        self.notesList.setObjectName("notesList")
        self.LeftColumn.addWidget(self.notesList)
        self.horizontalLayout.addLayout(self.LeftColumn)
        self.RightColumn = QtWidgets.QVBoxLayout()
        self.RightColumn.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.RightColumn.setSpacing(6)
        self.RightColumn.setObjectName("RightColumn")
        self.noteDataLAyout = QtWidgets.QHBoxLayout()
        self.noteDataLAyout.setContentsMargins(-1, -1, -1, 0)
        self.noteDataLAyout.setObjectName("noteDataLAyout")
        self.noteTitle = QtWidgets.QLineEdit(self.MainLayout)
        self.noteTitle.setMinimumSize(QtCore.QSize(0, 30))
        self.noteTitle.setMaximumSize(QtCore.QSize(16777215, 30))
        self.noteTitle.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(66, 39, 75, 255), stop:1 rgba(86, 59, 95, 255));\n"
"border: 2px solid rgb(65,48, 70);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);")
        self.noteTitle.setText("")
        self.noteTitle.setObjectName("noteTitle")
        self.noteDataLAyout.addWidget(self.noteTitle)
        self.saveNote = QtWidgets.QPushButton(self.MainLayout)
        self.saveNote.setMinimumSize(QtCore.QSize(100, 30))
        self.saveNote.setMaximumSize(QtCore.QSize(100, 30))
        self.saveNote.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveNote.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(106, 79, 115, 255), stop:1 rgba(128, 86, 146, 255));\n"
"border: 2px solid rgb(65,48, 70);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../e24d6e15/device-floppy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveNote.setIcon(icon3)
        self.saveNote.setObjectName("saveNote")
        self.noteDataLAyout.addWidget(self.saveNote)
        self.deleteNote = QtWidgets.QPushButton(self.MainLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteNote.sizePolicy().hasHeightForWidth())
        self.deleteNote.setSizePolicy(sizePolicy)
        self.deleteNote.setMinimumSize(QtCore.QSize(100, 30))
        self.deleteNote.setMaximumSize(QtCore.QSize(100, 30))
        self.deleteNote.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteNote.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(106, 79, 115, 255), stop:1 rgba(128, 86, 146, 255));\n"
"border: 2px solid rgb(65,48, 70);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../98a7b91/trash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteNote.setIcon(icon4)
        self.deleteNote.setObjectName("deleteNote")
        self.noteDataLAyout.addWidget(self.deleteNote)
        self.RightColumn.addLayout(self.noteDataLAyout)
        self.NoteText = QtWidgets.QTextEdit(self.MainLayout)
        self.NoteText.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(106, 79, 115, 255), stop:1 rgba(148, 106, 166, 255));\n"
"border: 2px solid rgb(65,48, 70);\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);")
        self.NoteText.setObjectName("NoteText")
        self.RightColumn.addWidget(self.NoteText)
        self.horizontalLayout.addLayout(self.RightColumn)
        MainWindow.setCentralWidget(self.MainLayout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Замітки"))
        self.createNote.setText(_translate("MainWindow", "Створити замітку"))
        self.searchNoteTxt.setPlaceholderText(_translate("MainWindow", "Пошук замітки..."))
        self.searchButton.setText(_translate("MainWindow", "Пошук"))
        self.noteTitle.setPlaceholderText(_translate("MainWindow", "Назва замітки..."))
        self.saveNote.setText(_translate("MainWindow", "Зберігти "))
        self.deleteNote.setText(_translate("MainWindow", "Видалити"))
        self.NoteText.setPlaceholderText(_translate("MainWindow", "Текст замітки..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
